<envEvento xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00">
    <idLote>000000000001</idLote>
    <evento versao="1.00">
      <infEvento Id="ID210200352302123456780001235500100000000110000000011">
        <cOrgao>35</cOrgao>
        <tpAmb>2</tpAmb>
        <CNPJ>12345678000123</CNPJ>
        <chNFe>35230212345678000123550010000000011000000001</chNFe>
        <dhEvento>2025-01-21T12:00:00-03:00</dhEvento>
        <tpEvento>210200</tpEvento>
        <nSeqEvento>1</nSeqEvento>
        <verEvento>1.00</verEvento>
        <detEvento versao="1.00">
          <descEvento>Confirmacao da Operacao</descEvento>
        </detEvento>
      </infEvento>
    </evento>
  </envEvento>